spring:
  application:
    name: TalentNexus
  datasource:
    url: jdbc:postgresql://rm-cn-8ly3w3yz200011ho.rwlb.rds.aliyuncs.com:5432/talentnexus
    username: psqluser
    password: 031006wj-
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      database: 1
      port: 6379
      host: localhost

server:
  port: 8081
